package com.ufc.backend.service;

import com.ufc.backend.dto.WeightClassRequest;
import com.ufc.backend.dto.WeightClassResponse;
import com.ufc.backend.entities.WeightClass;
import com.ufc.backend.repository.WeightClassRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Unit test: the repository is mocked, so this exercises only
 * WeightClassService's own logic (DTO <-> entity mapping) — no Spring
 * context, no database, runs in milliseconds.
 */
@ExtendWith(MockitoExtension.class)
class WeightClassServiceTest {

    @Mock
    private WeightClassRepository weightClassRepository;

    private WeightClassService weightClassService;

    @Test
    void addWeightClass_mapsRequestToEntity_andSavedEntityToResponse() {
        weightClassService = new WeightClassService(weightClassRepository);

        WeightClassRequest request = new WeightClassRequest("Lightweight", 65.8, 70.3);

        WeightClass saved = WeightClass.builder()
                .weightClassId(1L)
                .className("Lightweight")
                .minWeight(65.8)
                .maxWeight(70.3)
                .build();
        when(weightClassRepository.save(org.mockito.ArgumentMatchers.any(WeightClass.class))).thenReturn(saved);

        WeightClassResponse response = weightClassService.addWeightClass(request);

        // The request's values must reach the entity that gets persisted...
        ArgumentCaptor<WeightClass> captor = ArgumentCaptor.forClass(WeightClass.class);
        verify(weightClassRepository).save(captor.capture());
        WeightClass persisted = captor.getValue();
        assertThat(persisted.getWeightClassId()).isNull(); // never set by the client, must be generated by the DB
        assertThat(persisted.getClassName()).isEqualTo("Lightweight");
        assertThat(persisted.getMinWeight()).isEqualTo(65.8);
        assertThat(persisted.getMaxWeight()).isEqualTo(70.3);

        // ...and the saved entity's generated id must come back in the response.
        assertThat(response.weightClassId()).isEqualTo(1L);
        assertThat(response.className()).isEqualTo("Lightweight");
    }

    @Test
    void getAllWeightClassesAsStream_mapsEachEntityToAResponse() {
        weightClassService = new WeightClassService(weightClassRepository);

        WeightClass wc1 = WeightClass.builder().weightClassId(1L).className("Featherweight").minWeight(61.0).maxWeight(65.8).build();
        WeightClass wc2 = WeightClass.builder().weightClassId(2L).className("Lightweight").minWeight(65.8).maxWeight(70.3).build();
        when(weightClassRepository.streamAllWeightClasses()).thenReturn(Stream.of(wc1, wc2));

        List<WeightClassResponse> result = weightClassService.getAllWeightClassesAsStream();

        assertThat(result).hasSize(2);
        assertThat(result).extracting(WeightClassResponse::className)
                .containsExactly("Featherweight", "Lightweight");
    }
}
